---
- name: Add sentry apt key
  ansible.builtin.get_url:
    url: https://apt.mysentrykiosk.dev/doordeck.asc
    mode: '0644'
    dest: /usr/share/keyrings/doordeck.gpg

- name: Ensure outdated apt repository URL is not used
  ansible.builtin.apt_repository:
    repo: deb [arch=all signed-by=/usr/share/keyrings/doordeck.gpg] https://d1a5u3fbv6g2i0.cloudfront.net stable main
    filename: sentry
    state: absent

- name: Setup sentry apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=all signed-by=/usr/share/keyrings/doordeck.gpg] https://apt.mysentrykiosk.dev/ stable main
    filename: sentry
    update_cache: true

- name: Install jester authentication sidecar
  ansible.builtin.apt:
    state: present
    name: sentry-jester=1.16.0

- name: Permit Jester to restart GDM
  ansible.builtin.copy:
    dest: /etc/sudoers.d/jester
    owner: root
    group: root
    mode: '0440'
    content: |
      Cmnd_Alias JESTER_CMDS = /usr/bin/systemctl restart gdm
      jester ALL=(ALL) NOPASSWD: JESTER_CMDS
    validate: 'visudo -cf %s'
