---
- name: Add sentry apt key
  ansible.builtin.get_url:
    url: https://apt.mysentrykiosk.dev/doordeck.asc
    mode: '0644'
    dest: /usr/share/keyrings/doordeck.gpg

- name: Ensure outdated apt repository URL is not used
  ansible.builtin.apt_repository:
    repo: deb [arch=all signed-by=/usr/share/keyrings/doordeck.gpg] https://d1a5u3fbv6g2i0.cloudfront.net stable main
    filename: sentry
    state: absent

- name: Setup sentry apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=all signed-by=/usr/share/keyrings/doordeck.gpg] https://apt.mysentrykiosk.dev/ stable main
    filename: sentry
    update_cache: true

- name: Install jester authentication sidecar
  ansible.builtin.apt:
    state: latest
    name: sentry-jester
