common_ansible_pull_url: https://github.com/Sentry-Interactive/kiosk-playbook.git
common_ansible_pull_timer: |
  OnBootSec=5m
  OnCalendar=*-*-* 05:00:00
  RandomizedDelaySec=30m
common_hostname: "MA{{ ansible_default_ipv4.macaddress[-10:] | replace(':', '') | upper | string }}"
