---
# Alternative approach using GDM and whatever browser works
- name: Add group for kiosk user
  ansible.builtin.group:
    name: kiosk
    state: present

- name: Add user account for kiosk
  ansible.builtin.user:
    name: kiosk
    comment: Kiosk
    shell: /usr/sbin/nologin
    group: kiosk
    groups: video

- name: Install GDM, browsers and other tools
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - gdm3
      - firefox
      - chromium-browser
      - tigervnc-scraping-server
      - dbus-x11
      - xinput
      - alsa-utils
      - unclutter

- name: Stop GDM
  ansible.builtin.service:
    name: gdm
    state: stopped

- name: Ensure Chromium is up to date
  ansible.builtin.command: snap refresh chromium --channel="{{ kiosk_gdm_chromium_channel }}"
  register: result
  changed_when: '"has no updates available" not in result.stderr'
  ignore_errors: true

- name: Configure GDM as default
  ansible.builtin.copy:
    dest: /etc/X11/default-display-manager
    mode: '0644'
    content: |
      /usr/sbin/gdm3

- name: Configure GDM to autologin
  ansible.builtin.copy:
    dest: /etc/gdm3/custom.conf
    mode: '0644'
    content: |
      [daemon]
      AutomaticLoginEnable=True
      AutomaticLogin=kiosk

- name: Configure Kiosk Firefox XSession
  ansible.builtin.copy:
    dest: /usr/share/xsessions/kiosk-firefox.desktop
    mode: '0644'
    content: |
      [Desktop Entry]
      Type=Application
      Exec=firefox -kiosk "{{ kiosk_gdm_kiosk_ui_url }}"
      Name=Sentry Kiosk (Firefox)
      Comment=Sentry Kiosk (Firefox)

- name: Configure Kiosk Chromium XSession
  ansible.builtin.copy:
    dest: /usr/share/xsessions/kiosk-chromium.desktop
    mode: '0644'
    content: |
      [Desktop Entry]
      Type=Application
      Exec=chromium-browser -kiosk "{{ kiosk_gdm_kiosk_ui_url }}"
      Name=Sentry Kiosk (Chromium)
      Comment=Sentry Kiosk (Chromium)

- name: Set Kiosk XSession as default
  ansible.builtin.copy:
    dest: /var/lib/AccountsService/users/kiosk
    mode: '0600'
    owner: root
    group: root
    context: |
      [User]
      Session=kiosk-chromium
      SystemAccount=false
      
      [InputSource0]
      xkb=us

- name: Create 'managed' directory for Chromium configuration
  ansible.builtin.file:
    path: /etc/chromium-browser/policies/managed
    state: directory
    mode: '0755'

- name: Create 'recommended' directory for Chromium configuration
  ansible.builtin.file:
    path: /etc/chromium-browser/policies/recommended
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Setup Chromium managed policy
  ansible.builtin.template:
    dest: /etc/chromium-browser/policies/managed/chrome.json
    mode: '0644'
    src: chrome.json

- name: Create Firefox policy directory
  ansible.builtin.file:
    path: /etc/firefox/policies
    state: directory
    mode: '0755'

- name: Setup Firefox managed policy
  ansible.builtin.template:
    dest: /etc/firefox/policies/policies.json
    mode: '0644'
    src: policies.json

- name: Create VNC config directory
  ansible.builtin.file:
    path: /home/kiosk/.vnc
    owner: kiosk
    group: kiosk
    state: directory
    mode: '0700'

- name: Set VNC password to 'sentry' (VNC is only accessible view localhost)
  ansible.builtin.copy:
    dest: /home/kiosk/.vnc/passwd
    owner: kiosk
    group: kiosk
    mode: '0600'
    content: '{{ "NLrBqPxZGKk=" | b64decode }}'

- name: Enable unclutter to hide cursor
  ansible.builtin.copy:
    dest: /etc/default/unclutter
    mode: '0644'
    content: |
      START_UNCLUTTER=true
      EXTRA_OPTS="-idle 0"

- name: Create directory for custom scripts
  ansible.builtin.file:
    path: /home/kiosk/.config/sentry
    state: directory
    owner: kiosk
    group: kiosk
    mode: '0755'

- name: Create script for rotating screen
  ansible.builtin.copy:
    src: files/rotate
    dest: /home/kiosk/.config/sentry/rotate
    owner: kiosk
    group: kiosk
    mode: '0755'

- name: Create startup script
  ansible.builtin.copy:
    src: files/startup
    dest: /home/kiosk/.config/sentry/startup
    owner: kiosk
    group: kiosk
    mode: '0755'

- name: Create .xsessionrc file to start VNC on login
  ansible.builtin.copy:
    dest: /home/kiosk/.xsessionrc
    owner: kiosk
    group: kiosk
    mode: '0600'
    content: |
      ~/.config/sentry/rotate
      ~/.config/sentry/startup
      x0vncserver -AlwaysShared -AcceptPointerEvents=false AcceptKeyEvents=false -rfbauth ~/.vnc/passwd
      xset -dpms
      xset s off
      gsettings set org.gnome.settings-daemon.plugins.power idle-dim false

- name: Start GDM
  ansible.builtin.service:
    name: gdm
    state: started
