- name: Install ansible
  ansible.builtin.apt:
    name: ansible-core

# TODO
# Setup ansible-pull cron job
# Ensure requirements are installed

- name: Set hostname using MAC Address
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Update hosts file
  ansible.builtin.copy:
    dest: /etc/hosts
    content: |
      127.0.0.1 localhost
      127.0.1.1 {{ hostname }}
      
      # The following lines are desirable for IPv6 capable hosts
      ::1     ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      
- name: Install ansible-pull services
  ansible.builtin.template:
    dest: /etc/systemd/system
    src: "{{ item }}"
  loop:
    - ansible-pull.service
    - ansible-pull.timer

- name: Enable ansible-pull timer
  ansible.builtin.service:
    name: ansible-pull.timer
    state: started
    enabled: yes

- name: Setup management user group 
  ansible.builtin.group:
    name: sentry
    state: present

- name: Setup management user account
  ansible.builtin.user:
    name: sentry
    group: sentry
    groups: sudo
    shell: /usr/bin/bash

- name: Create .ssh directory
  ansible.builtin.file:
    path: /home/sentry/.ssh/
    state: directory
    owner: sentry
    group: sentry
    mode: '0700'

- name: Setup management SSH key
  ansible.builtin.copy:
    dest: /home/sentry/.ssh/authorized_keys
    mode: '0600'
    owner: sentry
    group: sentry
    content: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEwGHYkaDYnZWuA+tEJ+rJY7mnv3MXAHiY7ch2+KBHUR sentry
      
- name: Enable sudo without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'