---
- name: Install ubuntu-frame
  community.general.snap:
    name:
      - ubuntu-frame
    options:
      - daemon=true

- name: Install wpe-webkit-mir-kiosk
  community.general.snap:
    name:
      - wpe-webkit-mir-kiosk
    options:
      - daemon=true
      - url={{ kiosk_ui_url }}
      - error-to-console=true

- name: Snap Packages - Setup Plugs
  changed_when: false
  shell: 'snap connect {{ item.app }}:{{ item.plug }}'
  with_items:
    - plug: wayland
      app: wpe-webkit-mir-kiosk