#!/bin/bash

#Volume Control - turn up all volume output to 100%

pulseaudio --start

amixer set "Master" 70%
amixer set "Headphone" 70%
amixer set "Speaker" 70%


#Make external microphone the primary device 
DEVICE_NAME="alsa_input.usb-0c76"
if pacmd list-sources | grep -B 2  "$DEVICE_NAME"; then
        MIC_INDEX=$(pacmd list-sources | grep -B 2 "$DEVICE_NAME" | awk '/index:/ {print $2}')
        # Set default input device
        pacmd set-default-source "$MIC_INDEX"
fi
